<select name="ContentObjectAttribute_ezstring_data_text_{$attribute.id}" style="width: 80px;">
{def $state=$attribute.content|wash()}
            <option value=""></option>
              <optgroup label="USA">
                <option  {if eq($state,'AL')} selected="selected" {/if} >AL</option>
                <option  {if eq($state,'AK')} selected="selected" {/if} >AK</option>
                <option  {if eq($state,'AS')} selected="selected" {/if} >AS</option>
                <option  {if eq($state,'AZ')} selected="selected" {/if} >AZ</option>
                <option  {if eq($state,'AR')} selected="selected" {/if} >AR</option>
                <option  {if eq($state,'CA')} selected="selected" {/if} >CA</option>
                <option  {if eq($state,'CO')} selected="selected" {/if} >CO</option>
                <option  {if eq($state,'CT')} selected="selected" {/if} >CT</option>
                <option  {if eq($state,'DE')} selected="selected" {/if} >DE</option>
                <option  {if eq($state,'DC')} selected="selected" {/if} >DC</option>
                <option  {if eq($state,'FM')} selected="selected" {/if} >FM</option>
                <option  {if eq($state,'FL')} selected="selected" {/if} >FL</option>
                <option  {if eq($state,'GA')} selected="selected" {/if} >GA</option>
                <option  {if eq($state,'GU')} selected="selected" {/if} >GU</option>
                <option  {if eq($state,'HI')} selected="selected" {/if} >HI</option>
                <option  {if eq($state,'ID')} selected="selected" {/if} >ID</option>
                <option  {if eq($state,'IL')} selected="selected" {/if} >IL</option>
                <option  {if eq($state,'IN')} selected="selected" {/if} >IN</option>
                <option  {if eq($state,'IA')} selected="selected" {/if} >IA</option>
                <option  {if eq($state,'KS')} selected="selected" {/if} >KS</option>
                <option  {if eq($state,'KY')} selected="selected" {/if} >KY</option>
                <option  {if eq($state,'LA')} selected="selected" {/if} >LA</option>
                <option  {if eq($state,'ME')} selected="selected" {/if} >ME</option>
                <option  {if eq($state,'MH')} selected="selected" {/if} >MH</option>
                <option  {if eq($state,'MD')} selected="selected" {/if} >MD</option>
                <option  {if eq($state,'MA')} selected="selected" {/if} >MA</option>
                <option  {if eq($state,'MI')} selected="selected" {/if} >MI</option>
                <option  {if eq($state,'MN')} selected="selected" {/if} >MN</option>
                <option  {if eq($state,'MS')} selected="selected" {/if} >MS</option>
                <option  {if eq($state,'MO')} selected="selected" {/if} >MO</option>
                <option  {if eq($state,'MT')} selected="selected" {/if} >MT</option>
                <option  {if eq($state,'NE')} selected="selected" {/if} >NE</option>
                <option  {if eq($state,'NV')} selected="selected" {/if} >NV</option>
                <option  {if eq($state,'NH')} selected="selected" {/if} >NH</option>
                <option  {if eq($state,'NJ')} selected="selected" {/if} >NJ</option>
                <option  {if eq($state,'NM')} selected="selected" {/if} >NM</option>
                <option  {if eq($state,'NY')} selected="selected" {/if} >NY</option>
                <option  {if eq($state,'NC')} selected="selected" {/if} >NC</option>
                <option  {if eq($state,'ND')} selected="selected" {/if} >ND</option>
                <option  {if eq($state,'MP')} selected="selected" {/if} >MP</option>
                <option  {if eq($state,'OH')} selected="selected" {/if} >OH</option>
                <option  {if eq($state,'OK')} selected="selected" {/if} >OK</option>
                <option  {if eq($state,'OR')} selected="selected" {/if} >OR</option>
                <option  {if eq($state,'PW')} selected="selected" {/if} >PW</option>
                <option  {if eq($state,'PA')} selected="selected" {/if} >PA</option>
                <option  {if eq($state,'PR')} selected="selected" {/if} >PR</option>
                <option  {if eq($state,'RI')} selected="selected" {/if} >RI</option>
                <option  {if eq($state,'SC')} selected="selected" {/if} >SC</option>
                <option  {if eq($state,'SD')} selected="selected" {/if} >SD</option>
                <option  {if eq($state,'TN')} selected="selected" {/if} >TN</option>
                <option  {if eq($state,'TX')} selected="selected" {/if} >TX</option>
                <option  {if eq($state,'UT')} selected="selected" {/if} >UT</option>
                <option  {if eq($state,'VT')} selected="selected" {/if} >VT</option>
                <option  {if eq($state,'VI')} selected="selected" {/if} >VI</option>
                <option  {if eq($state,'VA')} selected="selected" {/if} >VA</option>
                <option  {if eq($state,'WA')} selected="selected" {/if} >WA</option>
                <option  {if eq($state,'WV')} selected="selected" {/if} >WV</option>
                <option  {if eq($state,'WI')} selected="selected" {/if} >WI</option>
                <option  {if eq($state,'WY')} selected="selected" {/if} >WY</option>
             </optgroup>
             <optgroup label="Canada">
                <option  {if eq($state,'AB')} selected="selected" {/if} >AB</option>
                <option  {if eq($state,'BC')} selected="selected" {/if} >BC</option>
                <option  {if eq($state,'MB')} selected="selected" {/if} >MB</option>
                <option  {if eq($state,'NB')} selected="selected" {/if} >NB</option>
                <option  {if eq($state,'NF')} selected="selected" {/if} >NF</option>
                <option  {if eq($state,'NS')} selected="selected" {/if} >NS</option>
                <option  {if eq($state,'NT')} selected="selected" {/if} >NT</option>
                <option  {if eq($state,'ON')} selected="selected" {/if} >ON</option>
                <option  {if eq($state,'PE')} selected="selected" {/if} >PE</option>
                <option  {if eq($state,'PQ')} selected="selected" {/if} >PQ</option>
                <option  {if eq($state,'SK')} selected="selected" {/if} >SK</option>
                <option  {if eq($state,'YT')} selected="selected" {/if} >YT</option>
             </optgroup>
             <optgroup label="Mexico">
                <option  {if eq($state,'AG')} selected="selected" {/if} >AG</option>
                <option  {if eq($state,'BC')} selected="selected" {/if} >BC</option>
                <option  {if eq($state,'BS')} selected="selected" {/if} >BS</option>
                <option  {if eq($state,'CH')} selected="selected" {/if} >CH</option>
                <option  {if eq($state,'CL')} selected="selected" {/if} >CL</option>
                <option  {if eq($state,'CM')} selected="selected" {/if} >CM</option>
                <option  {if eq($state,'CO')} selected="selected" {/if} >CO</option>
                <option  {if eq($state,'CS')} selected="selected" {/if} >CS</option>
                <option  {if eq($state,'DF')} selected="selected" {/if} >DF</option>
                <option  {if eq($state,'DG')} selected="selected" {/if} >DG</option>
                <option  {if eq($state,'GR')} selected="selected" {/if} >GR</option>
                <option  {if eq($state,'GT')} selected="selected" {/if} >GT</option>
                <option  {if eq($state,'HG')} selected="selected" {/if} >HG</option>
                <option  {if eq($state,'JA')} selected="selected" {/if} >JA</option>
                <option  {if eq($state,'MI')} selected="selected" {/if} >MI</option>
                <option  {if eq($state,'MO')} selected="selected" {/if} >MO</option>
                <option  {if eq($state,'MX')} selected="selected" {/if} >MX</option>
                <option  {if eq($state,'NA')} selected="selected" {/if} >NA</option>
                <option  {if eq($state,'NL')} selected="selected" {/if} >NL</option>
                <option  {if eq($state,'OA')} selected="selected" {/if} >OA</option>
                <option  {if eq($state,'PU')} selected="selected" {/if} >PU</option>
                <option  {if eq($state,'QR')} selected="selected" {/if} >QR</option>
                <option  {if eq($state,'QT')} selected="selected" {/if} >QT</option>
                <option  {if eq($state,'SI')} selected="selected" {/if} >SI</option>
                <option  {if eq($state,'SL')} selected="selected" {/if} >SL</option>
                <option  {if eq($state,'SO')} selected="selected" {/if} >SO</option>
                <option  {if eq($state,'TB')} selected="selected" {/if} >TB</option>
                <option  {if eq($state,'TL')} selected="selected" {/if} >TL</option>
                <option  {if eq($state,'TM')} selected="selected" {/if} >TM</option>
                <option  {if eq($state,'VE')} selected="selected" {/if} >VE</option>
                <option  {if eq($state,'YU')} selected="selected" {/if} >YU</option>
                <option  {if eq($state,'ZA')} selected="selected" {/if} >ZA</option>
             </optgroup>
{undef $state}
</select>