{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $quantity=first_set( $attribute.content.quantity, 0 )
     $period=first_set( $attribute.content.period, 0 )}
<div class="block">

    <div class="element">
        <label>{'Quantity'|i18n('content/datatype/edit/xrowbillingcycle')}</label>
        <select id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_quantity" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" name="{$attribute_base}_data_billingcycle_quantity_{$attribute.id}">
            {for 1 to 100 as $i}
                <option value="{$i}"{if $i|eq($quantity)} selected="selected"{/if}>{$i}</option>
            {/for}
        </select>

    </div>

    <div class="element">
        <label>{'Period'|i18n('content/datatype/edit/xrowbillingcycle')}</label>
        <select id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_data_int" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" name="{$attribute_base}_data_billingcycle_period_{$attribute.id}">
            {foreach $attribute.content.text_array as $key => $item}
                <option value="{$key}"{if $key|eq($period)} selected="selected"{/if}>{$item|wash}</option>
            {/foreach}
        </select>
    </div>

    <div class="break"></div>

</div>
