{*?template charset=utf-8?*}
{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div class="shop-basket">

 <div style="float: right;">
            <img src={"images/freeshipping50.gif"|ezdesign} alt="Alcone Beauty Company free shipping when you spend fifty dollars or more. Limited to the first 5lbs." title="Alcone Beauty Company free shipping when you spend fifty dollars or more. Limited to the first 5lbs."/>
        </div>
<h2>{"Alcone Company Promotional Coupons"|i18n("design/template/workflow")}</h2>
    <br />
    <br />
    <div style="width: 100%;  color: #565969; font-size: 12px; font-weight: bold; background-color: #EBEEEF; float: left; padding-top: 5px; padding-bottom: 5px; padding-left: 5px;">
    <div style="float: left;">1. Cart</div>
    <div style="float: left; padding-left: 10px;">2. Billing &amp; Shipping</div>
    <div style="float: left; padding-left: 30px; color: #308d9d;">3. Coupon</div>
    <div style="float: left; padding-left: 30px;">4. Confirmation</div>
    <div style="float: left; padding-left: 30px;">5. Payment info</div>
    <div style="float: left; padding-left: 30px;">6. Order completed</div>
    <div style="float: left; padding-left: 30px;">7. Review reciept</div>
    </div>
    <div class="break"></div>
    <br />


<h3>Please enter a vaild coupon.</h3>
Alcone's "In The Know" Newsletter is a great source for "Internet Only" coupons. <br />

If you don't have any valid coupon, click "No Coupon" to skip this step.</p>
{if $process.event_state|eq(3)}
<div class="message-warning">
<h3>Sorry, not a valid coupon</h3>
<p>Sorry the coupon you have entered is invalid:</p>
<ul>
   <li>Invalid or expired coupon code.</li>
</ul>
</div>
{/if}
<form method="post" action={"shop/confirmorder"|ezurl}>

<div class="block">
    <div class="element">
        <label>Coupon code: <input type="input" name="{$base}_code_{$event.id}" value="{$event.data_text1}" /></label>
    </div>
</div>
<div class="block">
    <div class="element">
        <input class="shopbutton" type="submit" name="{$base}_SelectButton_{$event.id}"  value="{'Have coupon'|i18n('design/template/workflow')}" />
    </div>
    <div class="element">
        <input class="shopbutton" type="submit" name="{$base}_CancelButton_{$event.id}"  value="{'No coupon'|i18n('design/template/workflow')}" />
    </div>
</div>

</form>
</div>
