{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* Default search results lister *}
{let use_url_translation=ezini('URLTranslator','Translation')|eq('enabled')}
{def $search_result_header=false()}

{section show=$search_result}
<table class="list" width="100%" border="0" cellspacing="0" cellpadding="0">
{section show=$search_result_header}
<tr>
    <th></th>
    <th>{"Name"|i18n("design/standard/content/search")}</th>
    <th width="1">{"Class"|i18n("design/standard/content/search")}</th>
</tr>
{/section}
<tr><td colspan="3"><div id="dottedline_long"></div></td></tr>
<tr>
  {section name=SearchResult loop=$search_result show=$search_result sequence=array(bglight,bgdark)}
      <td width="20" align="left"><img src={"images/arrow.gif"|ezdesign()}></td>
      <td width="600" align="left">
      {switch match=$:item.class_identifier}
      {case match="press_release"}
            <a href={"/press"|ezurl()}  style="text-decoration: none;">
      {/case}
      {case match="faq"}
            <a href={concat("/know_it_all/(question)/", $:item.node_id)|ezurl()} style="text-decoration: none;">
      {/case}
      {case match="in_the_known"}
            <a href={concat("/know_it_all/(question)/", $:item.node_id)|ezurl()} style="text-decoration: none;">
      {/case}
      {case}
        <a href={$:item.url_alias|ezurl()}  style="text-decoration: none;">
      {/case}
      {/switch}
      {$:item.name}</a></td>
      <td  width="50" align="left"nowrap><label>{$:item.class_name}</label></td>
      
      {*
          {node_view_gui view=search sequence=$:sequence use_url_translation=$use_url_translation content_node=$:item}
      *}
      
  {delimiter modulo=1}
</tr>
<tr><td colspan="3"><div id="dottedline_long"></div></td></tr>
<tr>
  {/delimiter}
  {section-else}
  {/section}
</tr>
<tr><td colspan="3"><div id="dottedline_long"></div></td></tr>
</table>
{/section}

{/let}
