{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if $attribute.has_content}
<table class="list">
<tr>
<th>Code</th>
<td>{$attribute.content.code}</td>
</tr>
<tr>
<th>Discount</th>
<td>{$attribute.content.discount} 

{if $attribute.content.discount_type|eq(1)}
{'Flat (basket)'|i18n( 'design/standard/content/datatype' )}
{elseif $attribute.content.discount_type|eq(2)}
{'Free Shipping and Handling'|i18n( 'design/standard/content/datatype' )}
{else}
{'Percent (basket)'|i18n( 'design/standard/content/datatype' )}
{/if}

</td>
</tr>
<tr>
<th>Activation date</th>
<td>{$attribute.content.from.timestamp|l10n(shortdate)}</td>
</tr>
<tr>
<th>Expiry date</th>
<td>{$attribute.content.till.timestamp|l10n(shortdate)}</td>
</tr>
</table>
{/if}