{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div class="maincontentheader">
<h1>{"Coupon validation"|i18n("design/standard/workflow")}</h1>
</div>
<p>Please enter a vaild coupon, if you received one from our service. If you don't have any valid coupon, click "No coupon" to skip this step.</p>
{if $process.event_state|eq(3)}
<div class="message-warning">
<h2>Warning</h2>
<p>Required data is either missing or is invalid:</p>
<ul>
   <li>Invalid or expired coupon code.</li>
</ul>     
</div>
{/if}
<form method="post" action={"shop/confirmorder"|ezurl}>

<div class="block">
    <div class="element">
        <label>Coupon code: <input type="input" name="{$base}_code_{$event.id}" value="{$event.data_text1}" /></label>
    </div>
</div>
<div class="block">
    <div class="element">
        <input class="button" type="submit" name="{$base}_SelectButton_{$event.id}"  value="{'Have coupon'|i18n('design/standard/workflow')}" />
    </div>
    <div class="element">
        <input class="button" type="submit" name="{$base}_CancelButton_{$event.id}"  value="{'No coupon'|i18n('design/standard/workflow')}" />
    </div>
</div>

</form>
