#!/bin/bash
EXTENSION_NAME="eZ Paypal Payment Gateway"
EXTENSION_IDENTIFIER="ezpaypal"
EXTENSION_SUMMARY="Payment gateway for Paypal"
EXTENSION_LICENSE="GPL"
EXTENSION_VERSION="1.0"
EXTENSION_PUBLISH_VERSION="3.5"
EXTENSION_ARCHIVE_NAME="ezpaypal"
EXTENSION_PHP_VERSION="4.3.2"

EXTENSION_FILTER_FILES="INSTALL README FAQ"
