#!/bin/bash
EXTENSION_NAME="eZ Paypal Payment Gateway"
EXTENSION_IDENTIFIER="ezpaypal"
EXTENSION_SUMMARY="Payment gateway for Paypal"
EXTENSION_LICENSE="GPL"
EXTENSION_VERSION="1.1"
EXTENSION_PUBLISH_VERSION="4.0"
EXTENSION_ARCHIVE_NAME="ezpaypal"
EXTENSION_PHP_VERSION="5.2"

EXTENSION_FILTER_FILES="INSTALL README FAQ"
