<?php
// Automatically created cache file for the package format
// Do not modify this file

$CacheCodeDate = 1069339607;

$Parameters = array( "name" => "xrowecommerce_classes",
                     "development" => false,
                     "summary" => "xrowecommerce classes",
                     "description" => false,
                     "vendor" => false,
                     "vendor-dir" => false,
                     "priority" => false,
                     "type" => "contentclass",
                     "extension" => false,
                     "install_type" => "install",
                     "ezpublish" => array( "version" => "4.2.1",
                                           "named-version" => "4.2" ),
                     "maintainers" => array( array( "name" => "Anonymous User",
                                                    "email" => "nospam@ez.no",
                                                    "role" => "lead" ) ),
                     "packaging" => array( "timestamp" => 1265034940,
                                           "host" => "localhost",
                                           "packager" => false ),
                     "source" => false,
                     "documents" => array( array( "name" => "LICENCE",
                                                  "mime-type" => "text/plain",
                                                  "os" => false,
                                                  "data" => "This file is part of the package xrowecommerce_classes.\n\nThis package is free software; you can redistribute it and/or modify\nit under the terms of the GNU General Public License as published by\nthe Free Software Foundation; either version 2 of the License, or\n(at your option) any later version.\n\nThis package is distributed in the hope that it will be useful,\nbut WITHOUT ANY WARRANTY; without even the implied warranty of\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\nGNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License\nalong with this package; if not, write to the Free Software\nFoundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA\n",
                                                  "audience" => false ) ),
                     "groups" => array(),
                     "changelog" => array( array( "timestamp" => 1265034940,
                                                  "person" => "Anonymous User",
                                                  "email" => "nospam@ez.no",
                                                  "changes" => array( "Creation of package" ),
                                                  "release" => "1" ) ),
                     "file-list" => array(),
                     "simple-file-list" => array(),
                     "version-number" => "1.1-0",
                     "release-number" => "1",
                     "release-timestamp" => false,
                     "licence" => "GPL",
                     "state" => "alpha",
                     "dependencies" => array( "provides" => array( array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "xrow_product_category" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "xrow_product_review" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "xrow_product" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "manufacturer" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "coupon" ),
                                                                   array( "type" => "ezcontentclass",
                                                                          "name" => "contentclass",
                                                                          "value" => "client" ) ),
                                              "requires" => array(),
                                              "obsoletes" => array(),
                                              "conflicts" => array() ),
                     "install" => array( array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-xrow_product_category",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-xrow_product_review",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-xrow_product",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-manufacturer",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-coupon",
                                                "sub-directory" => "ezcontentclass" ),
                                         array( "content" => false,
                                                "type" => "ezcontentclass",
                                                "name" => false,
                                                "os" => false,
                                                "filename" => "class-client",
                                                "sub-directory" => "ezcontentclass" ) ),
                     "uninstall" => array( array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-xrow_product_category",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-xrow_product_review",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-xrow_product",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-manufacturer",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-coupon",
                                                  "sub-directory" => "ezcontentclass" ),
                                           array( "content" => false,
                                                  "type" => "ezcontentclass",
                                                  "name" => false,
                                                  "os" => false,
                                                  "filename" => "class-client",
                                                  "sub-directory" => "ezcontentclass" ) ) );
$InstallData = array();
$RepositoryPath = "var/storage/packages";
?>
