{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $types = hash('1','MasterCard','2','Visa','3','Discover','4','American Express','5','Eurocard')}
{if $attribute.content.has_stored_card}
    <p>{$types[$attribute.content.type]|wash}</p>
    {if $attribute.content.type|eq(5)}
        <p>{$attribute.content.ecname|wash}<br />
            {"Account number"|i18n('design/standard/content/datatype')}:
            {"X"|repeat(sub($attribute.content.accountnumber|count,3))}{$attribute.content.accountnumber|extract_right( 3 )|wash( xhtml )}
            <br />
            {"Bank code"|i18n('design/standard/content/datatype')}:
            {$attribute.content.bankcode|wash}
        </p>

    {else}
        <label>{"Current stored card"|i18n('design/standard/content/datatype')}</label>
        <p><strong>{$attribute.content.name|wash}</strong><br />
            XXXX-XXXX-XXXX-{$attribute.content.number|extract_right( 4 )|wash( xhtml )}<br />
            {"expires"|i18n('design/standard/content/datatype')} {$attribute.content.month}/{$attribute.content.year}
        </p>
    {/if}
{else}
    <p>
        {"No card stored."|i18n('design/standard/content/datatype')}
    </p>
{/if}