{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*?template charset=latin1?*}
{default enable_help=true() enable_link=true()}

{let name=Path
     nodename='hhh'
     path=$module_result.path
     reverse_path=array()}
  {section show=is_set($module_result.title_path)}
    {set path=$module_result.title_path}
  {/section}
  {section loop=$:path}

  {if $module_result.path|count|sub(1)|eq($:index)}
    {set nodename=$:item}
  {elseif $:index|ne(0)}
    {set reverse_path=$:reverse_path|array_prepend($:item)}
  {/if}
  
  {/section}

{set-block scope=root variable=site_title}
{$Path:nodename.text}: {section loop=$Path:reverse_path} {$:item.text|wash}{delimiter} / {/delimiter}{/section} / {$site.title|wash}
{/set-block}

{/let}

<title>
{if $module_result.content_info.node_id|eq(2)}
{$site.title|wash}: Professional Makeup Artists Premiere Online Store for Quality Cosmetics, Character Makeup, Tools, and Technical Training: Home
{else}
{$site_title}
{/if}
</title>
    

    {section show=and(is_set($#Header:extra_data),is_array($#Header:extra_data))}
      {section name=ExtraData loop=$#Header:extra_data}
      {$:item}
      {/section}
    {/section}

    {* check if we need a http-equiv refresh *}
    {section show=$site.redirect}
    <meta http-equiv="Refresh" content="{$site.redirect.timer}; URL={$site.redirect.location}" />

    {/section}

    {section name=HTTP loop=$site.http_equiv}

    <meta http-equiv="{$HTTP:key|wash}" content="{$HTTP:item|wash}" />

    {/section}

    {section name=meta loop=$site.meta}

{if and($module_result.content_info.class_identifier|eq('product'), $meta:key|eq('keywords') )} 
    <meta name="{$meta:key|wash}" content="{$meta:item|wash}, 
{def $product = fetch( 'content', 'node', hash(node_id, $module_result.content_info.node_id ) )}
{if $product.data_map.keywords.has_content}{foreach $product.data_map.keywords.content.keywords as $word}{$word}{delimiter}, {/delimiter}{/foreach}{/if}" />
{else}

   <meta name="{$meta:key|wash}" content="{$meta:item|wash}" />
{/if}
    {/section}

    <meta name="MSSmartTagsPreventParsing" content="TRUE" />
    <meta name="generator" content="eZ publish" />

    <script type="text/javascript" src={'javascript/overlib.js'|ezdesign}><!-- overLIB (c) Erik Bosrup --></script>

{section show=$enable_link}
    {include uri="design:link.tpl" enable_help=$enable_help enable_link=$enable_link}
{/section}

{/default}
