{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div class="block">
{foreach $class_attribute.content.card_gateway_array as $card_key => $card}
    <div class="element">
        <p>
            <strong>{$class_attribute.content.card_array[$card_key]|wash}</strong><br />
            {if $class_attribute.content.gateway[$card_key]|ne('')}
                {"using payment gateway"|i18n( 'design/standard/class/datatype' )}:<br />
                {$class_attribute.content['gateway_array'][$class_attribute.content.gateway[$card_key]].Name|wash}
            {else}
                {"disabled"|i18n( 'design/standard/class/datatype' )}
            {/if}
        </p>
    </div>
{/foreach}

</div>

