{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}
<p>Activation date:</p>
<div class="block"><div class="date">

<div class="element">

<label>{'Year'|i18n( 'design/standard/content/datatype' )}:</label>
<input type="text" name="{$attribute_base}_coupon_year_{$attribute.id}" size="5" value="{$attribute.content.from.year}" />
</div>

<div class="element">
<label>{'Month'|i18n( 'design/standard/content/datatype' )}:</label>
<input type="text" name="{$attribute_base}_coupon_month_{$attribute.id}" size="3" value="{$attribute.content.from.month}" />
</div>

<div class="element">
<label>{'Day'|i18n( 'design/standard/content/datatype' )}:</label>
<input type="text" name="{$attribute_base}_coupon_day_{$attribute.id}" size="3" value="{$attribute.content.from.day}" />
</div>

<div class="break"></div>
</div></div>

<p>Expiry date:</p>
<div class="block"><div class="date">
<div class="element">
<label>{'Year'|i18n( 'design/standard/content/datatype' )}:</label>
<input type="text" name="{$attribute_base}_coupon_till_year_{$attribute.id}" size="5" value="{$attribute.content.till.year}" />
</div>

<div class="element">
<label>{'Month'|i18n( 'design/standard/content/datatype' )}:</label>
<input type="text" name="{$attribute_base}_coupon_till_month_{$attribute.id}" size="3" value="{$attribute.content.till.month}" />
</div>

<div class="element">
<label>{'Day'|i18n( 'design/standard/content/datatype' )}:</label>
<input type="text" name="{$attribute_base}_coupon_till_day_{$attribute.id}" size="3" value="{$attribute.content.till.day}" />
</div>

<div class="break"></div>
</div></div>

<div class="block">

<div class="element">
<label>{'Code'|i18n( 'design/standard/content/datatype' )}:</label>
<input type="text" name="{$attribute_base}_coupon_code_{$attribute.id}" size="64" value="{$attribute.content.code}" />
</div>

</div>

<div class="block">

<div class="element">
<label>{'Discount'|i18n( 'design/standard/content/datatype' )}:</label>
<input type="text" name="{$attribute_base}_coupon_discount_{$attribute.id}" size="10" value="{$attribute.content.discount}" />
</div>

<div class="element">
<label>{'Type'|i18n( 'design/standard/content/datatype' )}:</label>
<select name="{$attribute_base}_coupon_discount_type_{$attribute.id}">
<option value="0" {if $attribute.content.discount_type|eq(0)} selected="selected"{/if}>{'Percent (basket)'|i18n( 'design/standard/content/datatype' )}</option>
<option value="1" {if $attribute.content.discount_type|eq(1)} selected="selected"{/if}>{'Flat (basket)'|i18n( 'design/standard/content/datatype' )}</option>
<option value="2" {if $attribute.content.discount_type|eq(2)} selected="selected"{/if}>{'Free Shipping and Handling'|i18n( 'design/standard/content/datatype' )}</option>
</select>
</div>

</div>

{/default}