{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<h1>{"Aftersale"|i18n("design/standard/workflow")}</h1>
{include uri="design:workflow/aftersale_preface.tpl"}

<form method="post" action={"shop/checkout"|ezurl}>

<div class="block">
    <div class="element">
        
    </div>
</div>
<div class="buttonblock">
        <input class="button" type="submit" name="Buy" value="{'Add to order'|i18n('design/standard/workflow')}" />
        <input class="button" type="submit" name="Cancel" value="{'No coupon'|i18n('design/standard/workflow')}" />
</div>

</form>
