{* DO NOT EDIT THIS FILE! Use an override template instead. *}

{def $selectedGatewaysTypes=$event.selected_gateways_types}
<div class="block">
<div class="element">
    <label>{"Type"|i18n("extension/xrowecommerce")}</label><div class="labelbreak"></div>
    <select name="WorkflowEvent_event_ezpaymentgateway_gateways_{$event.id}[]" size="5"  multiple>
         
        <option value="-1" {if $selectedGatewaysTypes|contains('-1')} selected="selected" {/if}>{"Any"|i18n("extension/xrowecommerce")}</option>
        {foreach $event.workflow_type.allowed_gateways as $Gateways}
            <option value="{$Gateways.value}" {if $selectedGatewaysTypes|contains($Gateways.value)} selected="selected" {/if}>{$Gateways.Name|wash}
            </option>
        {/foreach}
    </select>
</div>
</div>
<div class="block">
<div class="element">
<label><input {if $event.permissions}checked="checked" {/if}type="checkbox" value="1" name="WorkflowEvent_event_ezpaymentgateway_permissions_{$event.id}" > {"Use eZ Publish roles and policies for payment method selection."|i18n("extension/xrowecommerce")}</label>
</div>
</div>