{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{section show=$verify_user_email}
<div id="col_main" >
	<h2>{"User registered"|i18n("design/standard/user")|upcase()}</h2>
	<br />
<div class="feedback">
<p>
{'Your account was successfully created. An e-mail will be sent to the specified
e-mail address. You need to follow the instructions in that mail to activate
your account.'|i18n('design/standard/user')}
</p>
</div>
{section-else}
<div id="col_main" >
<h1>{"User registered"|i18n("design/standard/user")}</h1>
</div>

<div class="feedback">
<h2>{"Your account was successfully created."|i18n("design/standard/user")}</h2>
</div>
{/section}
</div>

<div style="width: 0px; height: 500px; float: left; display: inline;"></div>
<div id="col_right" >
    <form action={"/content/search/"|ezurl} method="get">
        <div style="vertical-align: middle;">
            <b><span style="font-family: Times; font-size: 14px;color: #308d9d; font-weight: normal;">SEARCH:</span></b>
            <input type="text" name="SearchText" value="keyword" size="15" class="searchbox">&nbsp;
            <input type="image" src={"images/go.gif"|ezdesign()} style="vertical-align:middle;">
            <div id="dottedline"></div>
        </div>
    </form>
<div style="width: 10px; height: 450px;"></div>
</div>