{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base='ContentObjectAttribute'
         html_class='half'}
         <div class="block">
         <div class="element">
<input {if $attribute.data_int|eq('2')} readonly="readonly"{/if} id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="{eq( $html_class, 'half' )|choose( 'box', 'halfbox' )} ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="text" size="20" name="{$attribute_base}_xrowtin_data_text_{$attribute.id}" value="{$attribute.data_text|wash( xhtml )}" />
</div>

{def $access=fetch( 'user', 'has_access_to',
                    hash( 'module',   'xrowecommerce',
                          'function', 'administrate' ) )}
 
{if $access}
<div class="element">
<select id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class=" ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" size="1" name="{$attribute_base}_xrowtin_status_{$attribute.id}">
<option value="0"{if $attribute.data_int|eq('0')} selected{/if}>{'not validated'|i18n( 'extension/xrowtin' )}</option>
<option value="1"{if $attribute.data_int|eq('1')} selected{/if} disabled>{'validated'|i18n( 'extension/xrowtin' )}</option>
<option value="2"{if $attribute.data_int|eq('2')} selected{/if}>{'validated by administration'|i18n( 'extension/xrowtin' )}</option>
</select>
</div>
{/if}
</div>
{/default}

